title: HIMSS 粉丝团
description: 对HIMSS各类报告、ppt的研究、分享和讨论，主要是方便手机端查看，无需自行储存pdf文件了。时间允许的情况下，后续应该会挑选部分译成中文把.
github:
  is_project_page: false
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman